from __future__ import annotations

"""
Single source of truth for user-facing button/select labels.
Keep these values aligned across /help text and Discord panel views.
"""

START_BUTTON_LABEL = "시작"
STOP_BUTTON_LABEL = "중지"
PANIC_BUTTON_LABEL = "패닉"
TICK_ONCE_BUTTON_LABEL = "즉시 판단"
MARGIN_BUDGET_BUTTON_LABEL = "증거금 설정"
ADVANCED_TOGGLE_LABEL = "고급설정"
SIMPLE_TOGGLE_LABEL = "간단모드"

RISK_BASIC_BUTTON_LABEL = "리스크 기본"
RISK_ADVANCED_BUTTON_LABEL = "리스크 고급"
TRAILING_BUTTON_LABEL = "트레일링 설정"
SYMBOL_LEVERAGE_BUTTON_LABEL = "심볼 레버리지"
UNIVERSE_SYMBOLS_BUTTON_LABEL = "심볼 설정"
UNIVERSE_REMOVE_SYMBOL_BUTTON_LABEL = "심볼 해제"

EXEC_MODE_SELECT_PLACEHOLDER = "실행모드"
SCHEDULER_INTERVAL_SELECT_PLACEHOLDER = "스캔 간격"
NOTIFY_INTERVAL_SELECT_PLACEHOLDER = "상태 알림 주기"
SCORING_SETUP_BUTTON_LABEL = "판단식 설정"

SIMPLE_PANEL_BUTTON_LABELS = (
    START_BUTTON_LABEL,
    STOP_BUTTON_LABEL,
    PANIC_BUTTON_LABEL,
    TICK_ONCE_BUTTON_LABEL,
    MARGIN_BUDGET_BUTTON_LABEL,
)

ADVANCED_PANEL_BUTTON_LABELS = (
    RISK_BASIC_BUTTON_LABEL,
    RISK_ADVANCED_BUTTON_LABEL,
    TRAILING_BUTTON_LABEL,
    SYMBOL_LEVERAGE_BUTTON_LABEL,
    UNIVERSE_SYMBOLS_BUTTON_LABEL,
    UNIVERSE_REMOVE_SYMBOL_BUTTON_LABEL,
    SCORING_SETUP_BUTTON_LABEL,
    SIMPLE_TOGGLE_LABEL,
)
