from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class TraderAPI(Protocol):
    async def get_status(self) -> dict[str, Any]: ...

    async def get_risk(self) -> dict[str, Any]: ...

    async def start(self) -> dict[str, Any]: ...

    async def stop(self) -> dict[str, Any]: ...

    async def panic(self) -> dict[str, Any]: ...

    async def tick_scheduler_now(self) -> dict[str, Any]: ...

    async def send_daily_report(self) -> dict[str, Any]: ...

    async def set_scheduler_interval(self, tick_sec: float) -> dict[str, Any]: ...

    async def set_value(self, key: str, value: Any) -> dict[str, Any]: ...

    async def set_config(self, config: dict[str, Any]) -> dict[str, Any]: ...

    async def set_symbol_leverage(self, symbol: str, leverage: float) -> dict[str, Any]: ...

    async def close_position(self, symbol: str) -> dict[str, Any]: ...

    async def close_all(self) -> dict[str, Any]: ...

    async def clear_cooldown(self) -> dict[str, Any]: ...

    async def preset(self, name: str) -> dict[str, Any]: ...

    async def aclose(self) -> None: ...
