from __future__ import annotations

from typing import Protocol, runtime_checkable

JSONScalar = str | int | float | bool | None
JSONValue = JSONScalar | list["JSONValue"] | dict[str, "JSONValue"]
JSONPayload = dict[str, JSONValue]


@runtime_checkable
class TraderAPI(Protocol):
    async def get_status(self) -> JSONPayload: ...

    async def get_risk(self) -> JSONPayload: ...

    async def start(self) -> JSONPayload: ...

    async def stop(self) -> JSONPayload: ...

    async def panic(self) -> JSONPayload: ...

    async def tick_scheduler_now(self) -> JSONPayload: ...

    async def send_daily_report(self) -> JSONPayload: ...

    async def set_scheduler_interval(self, tick_sec: float) -> JSONPayload: ...

    async def set_value(self, key: str, value: str) -> JSONPayload: ...

    async def set_config(self, config: JSONPayload) -> JSONPayload: ...

    async def set_symbol_leverage(self, symbol: str, leverage: float) -> JSONPayload: ...

    async def close_position(self, symbol: str) -> JSONPayload: ...

    async def close_all(self) -> JSONPayload: ...

    async def clear_cooldown(self) -> JSONPayload: ...

    async def preset(self, name: str) -> JSONPayload: ...

    async def aclose(self) -> None: ...
